### ISSUE TITLE
 if averaged_im[-1-i] > threshold: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by trunksn1** [trunksn1/GettoniDOro#1]
Apro l'immagine e poi la passo alla funzione splitanswers()
`im = cv2.imread(screenshot_name) # type == <class 'numpy.ndarray'>
splitanswers(im)`

La funzione tuttavia dà un errore 

> File "omissis\splitanswers.py", line 18, in splitanswers
    if averaged_im[-1-i] > threshold:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by frovaris** [comment]
Sorry, va fatta dopo la trasformazione dell'immagine in b/n altrimenti hai un array con una dimensione in più
